# Generated by Django 6.0.1 on 2026-02-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('RD', 'Research & Development'), ('DIR', 'Director'), ('SUP', 'Supply Chain'), ('PURCHASE', 'Purchasing')], max_length=25),
        ),
    ]
