# Generated by Django 6.0.1 on 2026-02-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('RD', 'Research & Development'), ('RD MANAGER', 'RD_MANAGER'), ('Supply Chain', 'Supply Chain'), ('Purchasing', 'Purchasing')], max_length=25),
        ),
    ]
