# Generated by Django 6.0.1 on 2026-01-30 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('shipment_method', models.CharField(choices=[('AIR', 'Air Freight'), ('SEA', 'Sea Freight'), ('XPRESS', 'Express')], default='XPRESS', max_length=12)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash'), ('CC', 'CreditCard'), ('VALU', 'Installement')], default='CC', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_order_quantity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('expected_delivery_period', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_components', to='components.component')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_components', to='suppliers.supplier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('supplier', 'component'), name='unique_supplier_component')],
            },
        ),
    ]
