# Generated by Django 6.0.1 on 2026-01-30 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('batch_no', models.CharField(unique=True)),
                ('expiry_date', models.DateField()),
                ('received_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AVL', 'Available'), ('EXP', 'Expired'), ('CON', 'Consumed'), ('QTN', 'Quarantined')], default='AVL', max_length=25)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='components.component')),
            ],
        ),
    ]
