# Generated by Django 6.0.1 on 2026-01-30 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentbatch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_batches', to='suppliers.supplier'),
        ),
        migrations.AddConstraint(
            model_name='componentbatch',
            constraint=models.UniqueConstraint(fields=('supplier', 'batch_no'), name='unique_batch_per_supplier'),
        ),
    ]
