# Generated by Django 5.2.5 on 2026-02-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentbatch',
            name='batch_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
