# Generated by Django 6.0.1 on 2026-01-30 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0002_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('DEL', 'Delivered'), ('CANCEL', 'Cancelled'), ('REJ', 'Rejected'), ('SHIP', 'Shipped'), ('HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('PARTIAL_REC', 'Partial Receive')], default='ISSUED', max_length=12)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_orders', to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ordered_unit', models.CharField(choices=[('Kg', 'Kilogram'), ('Mt', 'Meters'), ('Lt', 'Litres')], default='Kg', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_items', to='components.component')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'component'), name='unique_component_per_order')],
            },
        ),
    ]
