# Generated by Django 6.0.1 on 2026-01-30 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('justification', models.TextField()),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_requests', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_requests', to='products.productversion')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('decision_date', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('APP', 'Approved'), ('REJ', 'Rejected'), ('PEND', 'Pending')], max_length=15)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('trial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='approvals.trialrequest')),
            ],
        ),
    ]
