# Generated by Django 6.0.1 on 2026-02-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='decision',
            field=models.CharField(choices=[('APP', 'Approved'), ('REJ', 'Rejected'), ('PEND', 'Pended')], max_length=15),
        ),
    ]
