# Generated by Django 5.2.5 on 2026-02-07 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_alter_decision_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trialrequest',
            name='decision_maker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_trials', to=settings.AUTH_USER_MODEL),
        ),
    ]
