# Generated by Django 5.2.5 on 2026-02-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_type_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TRIAL', 'Trial Decision'), ('TRIAL_REQUEST', 'New Trial Request'), ('ORDER_QTY_CHANGE', 'Order Qty Change')], default='TRIAL', max_length=20),
        ),
    ]
