# Generated by Django 6.0.1 on 2026-01-30 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Dr', 'Draft'), ('Tr', 'Trial'), ('App', 'Approved'), ('Arch', 'Archived')], default='Dr', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('TRIAL', 'Trial'), ('APPROVED', 'Approved'), ('OBSOLETE', 'Obsolete')], default='DRAFT', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=10)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_usages', to='components.component')),
                ('product_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productversion')),
            ],
            options={
                'unique_together': {('component', 'product_version')},
            },
        ),
    ]
