# Generated by Django 6.0.1 on 2026-02-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productversion',
            unique_together={('product', 'version_no')},
        ),
    ]
